server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: FOOD-CATALOGUE-SERVICE
  datasource:
    url: jdbc:mysql://mydatabase.ckpukr9uz0r3.eu-north-1.rds.amazonaws.com:3306/foodcataloguedb
    password: Password123
    username: root
    hikari:
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
        